<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Validator\Constraints\ComplexPasswordValidator' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidator.php';
include_once $this->targetDirs[3].'/src/Validator/Constraints/ComplexPasswordValidator.php';

return $this->privates['App\Validator\Constraints\ComplexPasswordValidator'] = new \App\Validator\Constraints\ComplexPasswordValidator();
