<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\TokenGenerator' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Csrf/TokenGenerator/TokenGeneratorInterface.php';
include_once $this->targetDirs[3].'/src/Service/TokenGenerator.php';

return $this->privates['App\Service\TokenGenerator'] = new \App\Service\TokenGenerator(($this->privates['logger'] ?? $this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger()));
