<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.vbh71Ar' shared service.

return $this->privates['service_locator.vbh71Ar'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('captchaValidator' => function (): ?\App\Service\CaptchaValidator {
    return ($this->privates['App\Service\CaptchaValidator'] ?? $this->privates['App\Service\CaptchaValidator'] = new \App\Service\CaptchaValidator($this->getEnv('RECAPTCHA_KEY'), $this->getEnv('RECAPTCHA_SECRET')));
}, 'mailer' => function (): ?\App\Service\Mailer {
    return ($this->privates['App\Service\Mailer'] ?? $this->load(__DIR__.'/getMailerService.php'));
}, 'tokenGenerator' => function (): ?\App\Service\TokenGenerator {
    return ($this->privates['App\Service\TokenGenerator'] ?? $this->load(__DIR__.'/getTokenGeneratorService.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}));
