<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHX71mKn\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHX71mKn/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHX71mKn.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHX71mKn\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerHX71mKn\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'HX71mKn',
    'container.build_id' => '8c613704',
    'container.build_time' => 1517860949,
));
