<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI5hwYTh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI5hwYTh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerI5hwYTh.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerI5hwYTh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerI5hwYTh\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'I5hwYTh',
    'container.build_id' => '60ed4ec0',
    'container.build_time' => 1517854394,
));
